# Generated by Django 5.2.8 on 2025-12-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permis_conduire',
            field=models.ImageField(blank=True, null=True, upload_to='permis/photos/'),
        ),
    ]
