# Generated by Django 5.2.8 on 2026-03-09 07:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PRESTATAIRE', 'Prestataire'), ('ADMIN', 'Administrateur'), ('SUPPORT', 'Support')], default='CLIENT', max_length=20),
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('PRESTATAIRE', 'Prestataire'), ('ADMIN', 'Administrateur'), ('SUPPORT', 'Support')], default='CLIENT', max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pending_registrations',
                'indexes': [models.Index(fields=['email'], name='pending_reg_email_a1f163_idx')],
            },
        ),
    ]
