# Generated by Django 5.2.8 on 2026-02-06 01:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role_pendingregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_sessions',
                'indexes': [models.Index(fields=['user', 'is_used'], name='password_re_user_id_8b9535_idx'), models.Index(fields=['token'], name='password_re_token_76f177_idx')],
            },
        ),
    ]
