# Generated by Django 5.2.8 on 2026-03-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_permis_conduire_recto_verso'),
        ('users', '0008_alter_user_is_staff'),
    ]

    operations = [
    ]
