# Generated by Django 5.2.8 on 2025-12-18 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('secondary_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='drivers/photos/')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de permis')),
                ('license_category', models.CharField(blank=True, help_text='Ex: B, C', max_length=50, verbose_name='Catégorie')),
                ('license_issued_date', models.DateField(blank=True, null=True, verbose_name='Date de délivrance')),
                ('license_expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('license_photo', models.ImageField(blank=True, null=True, upload_to='drivers/licenses/', verbose_name='Scan du permis')),
                ('cin_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro CIN')),
                ('cin_recto', models.ImageField(blank=True, null=True, upload_to='drivers/cins/', verbose_name='Recto du CIN')),
                ('cin_verso', models.ImageField(blank=True, null=True, upload_to='drivers/cins/', verbose_name='Verso du CIN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
