# Generated by Django 5.2.8 on 2025-12-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driver_vehicule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicule',
        ),
    ]
