# Generated by Django 5.2.8 on 2025-12-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_remove_driver_vehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='residence_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/residence/', verbose_name='Certificat de résidence'),
        ),
    ]
