# Generated by Django 5.2.8 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_driver_residence_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tarif chauffeur'),
        ),
    ]
