# Generated by Django 5.2.8 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_driver_driver_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='residence_certificate',
            field=models.FileField(blank=True, null=True, upload_to='drivers/residence/', verbose_name='Certificat de résidence'),
        ),
        migrations.AddField(
            model_name='driver',
            name='residence_issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de délivrance certificat de résidence'),
        ),
        migrations.AddField(
            model_name='driver',
            name='residence_validity_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Validité certificat de résidence (mois)'),
        ),
    ]
