# Generated by Django 5.2.8 on 2025-12-18 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('RESERVATION', 'Réservation'), ('PAYMENT', 'Paiement'), ('MESSAGE', 'Message'), ('SYSTEM', 'Système')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('NEW_MESSAGE', 'Nouveau message'), ('STATUS_CHANGED', 'Statut modifié'), ('NEW_TICKET', 'Nouveau ticket')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
