# Generated by Django 5.2.8 on 2026-03-15 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_reservation'),
        ('vehicule', '0010_vehicledocuments_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vehicule.vehicule'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('RESERVATION', 'Réservation'), ('PAYMENT', 'Paiement'), ('MESSAGE', 'Message'), ('SYSTEM', 'Système'), ('VEHICLE', 'Véhicule')], max_length=30),
        ),
    ]
