# Generated by Django 5.2.8 on 2026-03-18 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notification_action_url_notification_metadata_and_more'),
        ('vehicule', '0010_vehicledocuments_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='metadata',
            new_name='extra_data',
        ),
        migrations.AddField(
            model_name='notification',
            name='vehicle_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vehicule.vehicledocuments'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('RESERVATION', 'Réservation'), ('PAYMENT', 'Paiement'), ('MESSAGE', 'Message'), ('SYSTEM', 'Système'), ('VEHICLE', 'Véhicule'), ('VEHICLE_DOCUMENT', 'Document véhicule')], max_length=30),
        ),
    ]
