from rest_framework.routers import DefaultRouter
from django.urls import path,include
from . import views
# # marketing hero viewsets
router = DefaultRouter()
router.register(r'reviews', views.ReviewViewSet, basename='ReviewViewSet')



urlpatterns = [
  # viewsets
    # The line `path('', include(router.urls)),` in the urlpatterns list is including the URLs
    # generated by the DefaultRouter for the viewsets registered with it.
    path('', include(router.urls)),
]