# Generated by Django 5.2.8 on 2025-12-18 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeleVehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusVehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEquipments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='vehicule.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie de véhicule',
                'verbose_name_plural': 'Catégories de véhicules',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name="Titre d'annonce")),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('numero_immatriculation', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'immatriculation")),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Numéro de série (VIN)')),
                ('type_vehicule', models.CharField(choices=[('TOURISME', 'Véhicule de tourisme'), ('UTILITAIRE', 'Véhicule utilitaire')], default='TOURISME', max_length=20, verbose_name='Type de véhicule')),
                ('nombre_places', models.PositiveIntegerField(default=5, verbose_name='Nombre de places')),
                ('nombre_portes', models.PositiveIntegerField(default=4, verbose_name='Nombre de portes')),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('kilometrage_actuel_km', models.PositiveIntegerField(default=0, verbose_name='Kilométrage actuel (km)')),
                ('volume_coffre_litres', models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume du coffre (L)')),
                ('adresse_localisation', models.TextField(verbose_name='Adresse de localisation')),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('zone', models.CharField(blank=True, help_text='Zone / quartier', max_length=100)),
                ('devise', models.CharField(default='MGA', max_length=10)),
                ('montant_caution', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant de la caution')),
                ('est_certifie', models.BooleanField(default=False, verbose_name='Véhicule certifié')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='Disponible à la location')),
                ('note_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Note moyenne')),
                ('nombre_locations', models.PositiveIntegerField(default=0, verbose_name='Nombre de locations')),
                ('nombre_favoris', models.PositiveIntegerField(default=0, verbose_name="Nombre d'ajouts en favoris")),
                ('description', models.TextField(blank=True)),
                ('conditions_particulieres', models.TextField(blank=True, verbose_name='Conditions particulières')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='vehicule.category', verbose_name='Catégorie')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='driver.driver', verbose_name='Chauffeur attitré')),
                ('equipements', models.ManyToManyField(blank=True, related_name='vehicules', to='vehicule.vehicleequipments')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='vehicule.marque', verbose_name='Marque')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='vehicule.modelevehicule', verbose_name='Modèle')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='vehicule.statusvehicule', verbose_name='Statut')),
                ('transmission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='vehicule.transmission', verbose_name='Boîte de vitesse')),
                ('type_carburant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='vehicule.fueltype', verbose_name='Type de carburant')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='vehicles/photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicule.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BLOCKED', 'Indisponible manuelle'), ('MAINTENANCE', 'Maintenance / Réparation'), ('RESERVED', 'Réservé automatiquement')], default='BLOCKED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='vehicule.vehicule')),
            ],
            options={
                'verbose_name': 'Disponibilité véhicule',
                'verbose_name_plural': 'Disponibilités véhicule',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_type', models.CharField(choices=[('URBAIN', 'Zone Urbaine'), ('PROVINCE', 'Province / Hors-ville')], default='URBAIN', max_length=20)),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par jour')),
                ('prix_heure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix par heure')),
                ('prix_mois', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix par mois')),
                ('prix_par_semaine', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix par semaine')),
                ('remise_par_heure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Remise par heure (%)')),
                ('remise_par_jour', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Remise par jour (%)')),
                ('remise_par_mois', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Remise par mois (%)')),
                ('remise_longue_duree_pourcent', models.DecimalField(blank=True, decimal_places=2, help_text='Exemple : 10.00 = -10% pour les longues durées', max_digits=5, null=True, verbose_name='Remise longue durée (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_grid', to='vehicule.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Grille Tarifaire',
                'verbose_name_plural': 'Grilles Tarifaires',
                'unique_together': {('vehicle', 'zone_type')},
            },
        ),
    ]
