# Generated by Django 5.2.8 on 2025-12-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleequipments',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix par jour (Ar)'),
        ),
    ]
