# Generated by Django 5.2.8 on 2025-12-19 08:42

import django.db.models.deletion
import uuid
import vehicule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_vehicleequipments_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carte_grise', models.FileField(blank=True, null=True, upload_to=vehicule.models.vehicle_doc_upload_path)),
                ('visite_technique', models.FileField(blank=True, null=True, upload_to=vehicule.models.vehicle_doc_upload_path)),
                ('assurance', models.FileField(blank=True, null=True, upload_to=vehicule.models.vehicle_doc_upload_path)),
                ('is_valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicule.vehicule')),
            ],
        ),
    ]
