# Generated by Django 5.2.8 on 2025-12-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0003_vehicledocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
