# Generated by Django 5.2.8 on 2025-12-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0004_vehicule_valide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='est_disponible',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Disponible à la location'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='titre',
            field=models.CharField(db_index=True, max_length=255, verbose_name="Titre d'annonce"),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('TOURISME', 'Véhicule de tourisme'), ('UTILITAIRE', 'Véhicule utilitaire')], db_index=True, default='TOURISME', max_length=20, verbose_name='Type de véhicule'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='ville',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
