# Generated by Django 5.2.8 on 2026-02-12 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicule", "0007_vehicule_est_coup_de_coeur"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleConditionReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("view_notes", models.JSONField(blank=True, default=dict)),
                ("saved_view_timestamps", models.JSONField(blank=True, default=dict)),
                ("points", models.JSONField(blank=True, default=list)),
                ("custom_photos_by_view", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_condition_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_report",
                        to="vehicule.vehicule",
                        verbose_name="Rapport d'état des lieux",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport d'état véhicule",
                "verbose_name_plural": "Rapports d'état véhicules",
            },
        ),
    ]
