# Generated by Django 5.2.4 on 2026-03-15

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicule", "0008_vehicleconditionreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehiculeFavorite",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="vehicule_favorites", to=settings.AUTH_USER_MODEL, verbose_name="Utilisateur"),
                ),
                (
                    "vehicle",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="favorited_by", to="vehicule.vehicule", verbose_name="Véhicule"),
                ),
            ],
            options={
                "verbose_name": "Favori véhicule",
                "verbose_name_plural": "Favoris véhicules",
                "ordering": ["-created_at"],
                "constraints": [models.UniqueConstraint(fields=("user", "vehicle"), name="unique_user_vehicle_favorite")],
            },
        ),
    ]
