# Generated by Django 5.2.8 on 2026-03-15 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0009_vehiculefavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledocuments',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicledocuments',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicledocuments',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vehicle_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicledocuments',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vehicules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_REVIEW', 'En attente de validation'), ('PUBLISHED', 'Publié'), ('REJECTED', 'Rejeté')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicledocuments',
            name='is_valide',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='valide',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
