# Generated by Django 5.2.8 on 2025-12-18 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driving_mode', models.CharField(choices=[('SELF_DRIVE', 'Je conduis (Self-drive)'), ('WITH_DRIVER', 'Avec chauffeur pro')], default='SELF_DRIVE', max_length=20)),
                ('pricing_zone', models.CharField(choices=[('URBAIN', 'Zone Urbaine'), ('PROVINCE', 'Province')], default='URBAIN', max_length=20)),
                ('driver_source', models.CharField(choices=[('NONE', 'Aucun (Self-drive)'), ('PROVIDER', 'Chauffeur Prestataire'), ('ADMIN_POOL', 'Pool Admin')], default='NONE', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('total_days', models.PositiveIntegerField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('options_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('with_chauffeur', models.BooleanField(default=False)),
                ('pickup_location', models.TextField()),
                ('dropoff_location', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(db_index=True, max_length=255)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payments/proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validé'), ('REJECTED', 'Rejeté'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('ASSURANCE', 'Assurance'), ('CHAUFFEUR', 'Chauffeur'), ('EQUIPEMENT', 'Équipement'), ('AUTRE', 'Autre')], max_length=20)),
                ('service_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
