# Generated by Django 5.2.8 on 2025-12-18 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0002_initial'),
        ('modepayment', '0001_initial'),
        ('reservations', '0001_initial'),
        ('vehicule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='driver.driver', verbose_name='Chauffeur assigné'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='vehicule.vehicule'),
        ),
        migrations.AddField(
            model_name='reservationpayment',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='modepayment.modepayment'),
        ),
        migrations.AddField(
            model_name='reservationpayment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservationpayment',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='reservationservice',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='reservations.reservation'),
        ),
    ]
