# Generated by Django 5.2.8 on 2025-12-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
        ('vehicule', '0002_vehicleequipments_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='vehicule.vehicleequipments', verbose_name='Équipements supplémentaires'),
        ),
    ]
