# Generated by Django 5.2.8 on 2025-12-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reference',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Référence unique auto-générée (ex: RES-20251219-0001)', max_length=20, unique=True),
        ),
    ]
