# Generated by Django 5.2.8 on 2025-12-23 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_initial'),
        ('vehicule', '0005_alter_vehicule_est_disponible_alter_vehicule_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_tickets', to='vehicule.vehicule'),
        ),
    ]
