# Generated by Django 5.2.8 on 2025-12-23 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_reference'),
        ('support', '0003_supportticket_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='reservations.reservation'),
        ),
    ]
