# Generated by Django 5.2.8 on 2025-12-18 11:11

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('CLIENT_TO_OWNER', 'Client → Propriétaire'), ('OWNER_TO_CLIENT', 'Propriétaire → Client')], help_text="Sens de l'avis : client vers propriétaire ou inverse.", max_length=32)),
                ('rating', models.PositiveSmallIntegerField(help_text='Note de 1 à 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text="Commentaire optionnel pour détailler l'expérience.")),
                ('is_verified', models.BooleanField(default=True, help_text="True si l'avis est lié à une réservation réellement effectuée.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'db_table': 'reviews',
                'ordering': ('-created_at',),
            },
        ),
    ]
