# Generated by Django 5.2.8 on 2025-12-18 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(help_text="Utilisateur qui a rédigé l'avis.", on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Réservation sur laquelle porte cet avis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='review',
            name='target',
            field=models.ForeignKey(blank=True, help_text="Utilisateur qui reçoit l'avis (client ou propriétaire).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('reservation__isnull', False)), fields=('reservation', 'author', 'review_type'), name='unique_review_per_reservation_and_direction'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('reservation__isnull', True)), fields=('author', 'target', 'review_type'), name='unique_review_without_reservation'),
        ),
    ]
