# Generated by Django 5.2.8 on 2025-12-18 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(help_text='Nom commercial ou entreprise', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='prestataires/logos/')),
                ('nif', models.CharField(help_text='Numéro NIF (Identifiant fiscal)', max_length=50, unique=True)),
                ('stat', models.CharField(help_text='Numéro STAT', max_length=50, unique=True)),
                ('rcs', models.CharField(blank=True, help_text='Numéro RCS (Registre du commerce)', max_length=50, null=True)),
                ('cif', models.CharField(blank=True, help_text='Code d’identification fiscale', max_length=50, null=True)),
                ('nif_document', models.FileField(blank=True, null=True, upload_to='prestataires/docs/nif/')),
                ('stat_document', models.FileField(blank=True, null=True, upload_to='prestataires/docs/stat/')),
                ('rcs_document', models.FileField(blank=True, null=True, upload_to='prestataires/docs/rcs/')),
                ('cif_document', models.FileField(blank=True, null=True, upload_to='prestataires/docs/cif/')),
                ('phone', models.CharField(max_length=50)),
                ('secondary_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'En attente de vérification'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('REJECTED', 'Rejeté')], default='PENDING_VERIFICATION', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
