# Generated by Django 5.2.8 on 2025-12-18 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestataire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestataire_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_prestataires', to=settings.AUTH_USER_MODEL),
        ),
    ]
